-- ЗАДАНИЕ 2. Анализ первичных и внешних ключей

-- Просмотр внешних ключей базы данных world через INFORMATION_SCHEMA
SELECT
  TABLE_NAME,
  COLUMN_NAME,
  CONSTRAINT_NAME,
  REFERENCED_TABLE_NAME,
  REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'world'
  AND REFERENCED_TABLE_NAME IS NOT NULL;
